# kopo_customer 데이터를 불러온 후 STATENAME컬럼만 STNAME으로 변경하세요.

In [1]:
## 패키지 불러오기
import pandas as pd
from sqlalchemy import create_engine

#DB커넥션 열기
engine = create_engine('oracle+cx_oracle://kopo:kopo@192.168.110.112:1521/orcl')

# DB 테이블을 읽어 Data Frame 변수에 저장하기
customerData = pd.read_sql_query('SELECT * FROM kopo_customerdata', engine)
customerData.head()

,customercode,statename,st,gender,dob,gender1,email,fest_cnt,total_amount,ac_amount,av_amount,ha_amount,emi_ce_amount,is_highend,cnt_vist,gap_visit
0,1503989,State2,2,Male,0,1,1,0,30300,0,30300,0,0,0,1,0
1,1190338,State2,2,Male,0,1,0,1,46500,0,46500,0,0,0,1,0
2,1424715,State2,2,Female,0,2,0,0,22700,0,0,22700,0,0,1,0
3,2483305,State2,2,Male,0,1,0,1,31400,0,31400,0,0,0,1,0
4,1178802,State2,2,Male,0,1,0,1,44900,0,0,44900,0,0,1,0

In [2]:
customerData.rename(columns={"statename": "stname"})

,customercode,stname,st,gender,dob,gender1,email,fest_cnt,total_amount,ac_amount,av_amount,ha_amount,emi_ce_amount,is_highend,cnt_vist,gap_visit
0,1503989,State2,2,Male,0,1,1,0,30300,0,30300,0,0,0,1,0
1,1190338,State2,2,Male,0,1,0,1,46500,0,46500,0,0,0,1,0
2,1424715,State2,2,Female,0,2,0,0,22700,0,0,22700,0,0,1,0
3,2483305,State2,2,Male,0,1,0,1,31400,0,31400,0,0,0,1,0
4,1178802,State2,2,Male,0,1,0,1,44900,0,0,44900,0,0,1,0
5,859044,State2,2,Male,0,1,0,0,38300,38300,0,0,0,0,1,0
6,734198,State2,2,Female,0,2,0,0,19900,0,0,19900,0,0,1,0
7,1443485,State2,2,Female,0,2,0,0,14800,0,0,14800,0,0,1,0
8,2340520,State2,2,Male,0,1,0,1,24400,0,0,24400,0,0,1,0
9,697949,State2,2,Male,0,1,0,1,30400,0,0,30400,0,0,1,0
10,385031,State2,2,Male,0,1,0,1,30300,0,0,30300,0,0,1,0
11,1944258,State2,2,Female,0,2,0,0,34300,0,18000,16300,0,0,1,0
12,2029521,State2,2,Female,0,2,0,0,14900,0,0,14900,0,0,1,0
13,1429192,State2,2,Male,0,1,0,0,16300,0,0,16300,0,0,1,0
14,892851,State2,2,Male,0,1,0,1,25000,0,0,25000,0,0,1,0
15,1554976,State2,2,Male,0,1,0,2,27500,0,0,27500,0,0,2,69
16,1154228,State2,2,Male,0,1,1,0,18200,0,0,18200,0,0,1,0
17,816582,State2,2,Male,0,1,0,1,40200,0,40200,0,0,0,2,940
18,675948,State2,2,Female,0,2,0,1,74600,0,0,74600,0,0,1,0
19,965940,State2,2,Male,0,1,0,0,42700,42700,0,0,0,0,1,0
20,2636314,State2,2,Male,0,1,0,0,14900,0,14900,0,0,0,1,0
21,577344,State2,2,Female,0,2,0,0,58700,0,24500,34200,0,0,2,21
22,910781,State2,2,Male,0,1,0,1,16000,0,16000,0,0,0,1,0
23,541107,State2,2,Female,0,2,0,1,17800,0,0,17800,0,0,1,0
24,1860112,State2,2,Male,0,1,0,0,26800,0,0,26800,0,0,1,0
25,1016762,State2,2,Male,1,1,0,1,14000,0,0,14000,0,0,1,0
26,2029821,State2,2,Male,0,1,0,0,31800,0,0,31800,0,0,1,0
27,765206,State2,2,Male,0,1,0,0,16000,0,0,16000,0,0,1,0
28,2174694,State2,2,Male,0,1,0,1,37600,0,0,37600,0,0,1,0
29,1196869,State2,2,Female,0,2,0,1,32800,0,16700,16100,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299970,2436525,State1,1,Male,0,1,0,1,67100,0,0,67100,0,0,1,0
299971,1238030,State1,1,Male,0,1,0,0,70100,0,55800,14300,0,0,3,663
299972,923009,State1,1,Male,0,1,0,1,17600,0,17600,0,0,0,1,0
299973,1433055,State1,1,Male,0,1,0,0,14200,0,0,14200,0,0,1,0
299974,2639022,State1,1,Male,0,1,0,0,66600,0,33000,33600,0,0,1,0
299975,1076615,State1,1,Male,0,1,0,1,35300,0,0,35300,0,0,1,0
299976,1017806,State1,1,Male,0,1,0,1,14900,0,0,14900,0,0,1,0
299977,1673649,State1,1,Male,0,1,0,2,26900,0,26900,0,0,0,2,511
299978,2304135,State1,1,Male,0,1,0,0,26300,0,26300,0,0,0,1,0
299979,726202,State1,1,Male,0,1,0,0,26300,0,26300,0,0,0,1,0
299980,2531738,State1,1,Male,0,1,0,0,13200,0,13200,0,0,0,1,0
299981,732024,State1,1,Male,0,1,0,0,13600,0,0,13600,0,0,1,0
299982,1829484,State1,1,Female,0,2,0,0,28500,0,0,28500,0,0,1,0
299983,923895,State1,1,Male,0,1,0,1,15600,0,15600,0,0,0,1,0
299984,2544242,State1,1,Male,0,1,0,0,18600,0,0,18600,0,0,1,0
299985,1006611,State1,1,Male,0,1,0,1,16500,0,0,16500,0,0,1,0
299986,1795625,State1,1,Male,0,1,0,1,18400,0,0,18400,0,0,1,0
299987,731422,State1,1,Male,0,1,0,0,14800,0,0,14800,0,0,1,0
299988,463974,State1,1,Male,0,1,0,0,20400,0,0,20400,0,0,1,0
299989,1274816,State1,1,Male,0,1,0,1,15900,0,15900,0,0,0,1,0
299990,2034458,State1,1,Male,0,1,0,0,24300,0,0,24300,0,0,1,0
299991,1349673,State1,1,Male,0,1,0,1,21200,0,0,21200,0,0,1,0
299992,1098613,State1,1,Male,0,1,0,0,14000,0,14000,0,0,0,1,0
299993,721218,State1,1,Male,0,1,0,0,31400,0,0,31400,0,0,1,0
299994,598593,State1,1,Male,0,1,0,0,29000,0,0,29000,0,0,1,0
299995,465757,State1,1,Male,0,1,0,0,40600,0,40600,0,0,0,1,0
299996,1890264,State1,1,Male,0,1,0,1,48000,48000,0,0,0,0,1,0
299997,1857537,State1,1,Female,0,2,0,0,32300,0,0,32300,0,0,1,0
299998,2209324,State1,1,Male,0,1,0,1,48500,0,48500,0,0,0,1,0
299999,1875146,State1,1,Male,0,1,0,1,16500,0,0,16500,0,0,1,0

In [3]:
## 변경된 칼럼명을 새로운 데이터 프레임에 저장
recustomerData = customerData.rename(columns={"statename": "stname"})
recustomerData.head()

,customercode,stname,st,gender,dob,gender1,email,fest_cnt,total_amount,ac_amount,av_amount,ha_amount,emi_ce_amount,is_highend,cnt_vist,gap_visit
0,1503989,State2,2,Male,0,1,1,0,30300,0,30300,0,0,0,1,0
1,1190338,State2,2,Male,0,1,0,1,46500,0,46500,0,0,0,1,0
2,1424715,State2,2,Female,0,2,0,0,22700,0,0,22700,0,0,1,0
3,2483305,State2,2,Male,0,1,0,1,31400,0,31400,0,0,0,1,0
4,1178802,State2,2,Male,0,1,0,1,44900,0,0,44900,0,0,1,0

In [4]:
## 패키지 불러오기
import pandas as pd
from sqlalchemy import create_engine

#DB커넥션 열기
engine = create_engine('oracle+cx_oracle://kopo:kopo@192.168.110.112:1521/orcl')

# DB 테이블을 읽어 Data Frame 변수에 저장하기
regionMasterData = pd.read_sql_query('SELECT * FROM kopo_region_mst', engine)
selectExample = pd.read_sql_query('SELECT * FROM kopo_channel_seasonality_new', engine)

In [5]:
regionMasterData.head()

  regionid regionname
0      A00       아프리카
1      A01         미국
2      A02         한국
3      A03         독일
4      A04        브라질

In [6]:
selectExample.head()

  regionid    product yearweek      qty
0      A60   PRODUCT4   201402     71.0
1      A60  PRODUCT59   201402  22275.0
2      A60  PRODUCT34   201402   4463.0
3      A60  PRODUCT47   201402      0.0
4      A60  PRODUCT56   201402     23.0

# groupby 지역 , 상품별 평균 판매량 구하기

In [7]:
groupData = selectExample.\
groupby(['regionid','product'], as_index=True)[["qty"]].\
mean()
groupData

                              qty
regionid product
A00      PRODUCT34     132.445860
         PRODUCT58     105.235669
         PRODUCT59   36086.547771
A01      PRODUCT1     5716.726115
         PRODUCT12  197052.777070
         PRODUCT14   17934.738854
         PRODUCT15    4759.554140
         PRODUCT16    1392.394904
         PRODUCT19    3335.140127
         PRODUCT2    22769.891720
         PRODUCT20      62.955414
         PRODUCT33   11919.828025
         PRODUCT34  108633.229299
         PRODUCT4    25851.547771
         PRODUCT47   10998.159236
         PRODUCT56    6296.229299
         PRODUCT57    6804.643312
         PRODUCT58   27346.216561
         PRODUCT59  642760.585987
         PRODUCT6      800.222930
         PRODUCT60       0.636943
         PRODUCT62   11378.993631
         PRODUCT63   47715.101911
         PRODUCT7     2080.101911
         PRODUCT75   30013.961783
         PRODUCT8      186.719745
A02      PRODUCT1      155.331210
         PRODUCT12    8995.910828
         PRODUCT14    1797.044586
         PRODUCT16      23.509554
...                           ...
A65      PRODUCT1       62.388535
         PRODUCT12    1114.828025
         PRODUCT14      16.834395
         PRODUCT33     122.942675
         PRODUCT34    1780.127389
         PRODUCT40       9.554140
         PRODUCT47      23.089172
         PRODUCT56      88.203822
         PRODUCT57      91.165605
         PRODUCT58     181.369427
         PRODUCT59   12114.452229
         PRODUCT60      82.159236
         PRODUCT62     187.605096
A66      PRODUCT34     176.936306
         PRODUCT58       4.789809
         PRODUCT59    3788.566879
A67      PRODUCT34     703.484076
         PRODUCT58      40.796178
         PRODUCT59   21489.286624
A68      PRODUCT34     290.184713
         PRODUCT58       1.649682
         PRODUCT59    7785.178344
A69      PRODUCT34     166.184713
         PRODUCT58       4.611465
         PRODUCT59    8320.515924
A70      PRODUCT34    2165.585987
         PRODUCT58      61.496815
         PRODUCT59   69471.617834
A77      PRODUCT1     2890.745223
         PRODUCT12    3473.324841

[794 rows x 1 columns]

In [8]:
## 인덱스를 풀어서 데이터 프레임 형태로 만들어주기
groupData  = selectExample.\
groupby(['regionid','product'], as_index=False)[["qty"]].\
mean()
groupData

    regionid    product            qty
0        A00  PRODUCT34     132.445860
1        A00  PRODUCT58     105.235669
2        A00  PRODUCT59   36086.547771
3        A01   PRODUCT1    5716.726115
4        A01  PRODUCT12  197052.777070
5        A01  PRODUCT14   17934.738854
6        A01  PRODUCT15    4759.554140
7        A01  PRODUCT16    1392.394904
8        A01  PRODUCT19    3335.140127
9        A01   PRODUCT2   22769.891720
10       A01  PRODUCT20      62.955414
11       A01  PRODUCT33   11919.828025
12       A01  PRODUCT34  108633.229299
13       A01   PRODUCT4   25851.547771
14       A01  PRODUCT47   10998.159236
15       A01  PRODUCT56    6296.229299
16       A01  PRODUCT57    6804.643312
17       A01  PRODUCT58   27346.216561
18       A01  PRODUCT59  642760.585987
19       A01   PRODUCT6     800.222930
20       A01  PRODUCT60       0.636943
21       A01  PRODUCT62   11378.993631
22       A01  PRODUCT63   47715.101911
23       A01   PRODUCT7    2080.101911
24       A01  PRODUCT75   30013.961783
25       A01   PRODUCT8     186.719745
26       A02   PRODUCT1     155.331210
27       A02  PRODUCT12    8995.910828
28       A02  PRODUCT14    1797.044586
29       A02  PRODUCT16      23.509554
..       ...        ...            ...
764      A65   PRODUCT1      62.388535
765      A65  PRODUCT12    1114.828025
766      A65  PRODUCT14      16.834395
767      A65  PRODUCT33     122.942675
768      A65  PRODUCT34    1780.127389
769      A65  PRODUCT40       9.554140
770      A65  PRODUCT47      23.089172
771      A65  PRODUCT56      88.203822
772      A65  PRODUCT57      91.165605
773      A65  PRODUCT58     181.369427
774      A65  PRODUCT59   12114.452229
775      A65  PRODUCT60      82.159236
776      A65  PRODUCT62     187.605096
777      A66  PRODUCT34     176.936306
778      A66  PRODUCT58       4.789809
779      A66  PRODUCT59    3788.566879
780      A67  PRODUCT34     703.484076
781      A67  PRODUCT58      40.796178
782      A67  PRODUCT59   21489.286624
783      A68  PRODUCT34     290.184713
784      A68  PRODUCT58       1.649682
785      A68  PRODUCT59    7785.178344
786      A69  PRODUCT34     166.184713
787      A69  PRODUCT58       4.611465
788      A69  PRODUCT59    8320.515924
789      A70  PRODUCT34    2165.585987
790      A70  PRODUCT58      61.496815
791      A70  PRODUCT59   69471.617834
792      A77   PRODUCT1    2890.745223
793      A77  PRODUCT12    3473.324841

[794 rows x 3 columns]

In [9]:
groupData = selectExample.groupby(["regionid","product"]).mean().reset_index()
groupData

    regionid    product            qty
0        A00  PRODUCT34     132.445860
1        A00  PRODUCT58     105.235669
2        A00  PRODUCT59   36086.547771
3        A01   PRODUCT1    5716.726115
4        A01  PRODUCT12  197052.777070
5        A01  PRODUCT14   17934.738854
6        A01  PRODUCT15    4759.554140
7        A01  PRODUCT16    1392.394904
8        A01  PRODUCT19    3335.140127
9        A01   PRODUCT2   22769.891720
10       A01  PRODUCT20      62.955414
11       A01  PRODUCT33   11919.828025
12       A01  PRODUCT34  108633.229299
13       A01   PRODUCT4   25851.547771
14       A01  PRODUCT47   10998.159236
15       A01  PRODUCT56    6296.229299
16       A01  PRODUCT57    6804.643312
17       A01  PRODUCT58   27346.216561
18       A01  PRODUCT59  642760.585987
19       A01   PRODUCT6     800.222930
20       A01  PRODUCT60       0.636943
21       A01  PRODUCT62   11378.993631
22       A01  PRODUCT63   47715.101911
23       A01   PRODUCT7    2080.101911
24       A01  PRODUCT75   30013.961783
25       A01   PRODUCT8     186.719745
26       A02   PRODUCT1     155.331210
27       A02  PRODUCT12    8995.910828
28       A02  PRODUCT14    1797.044586
29       A02  PRODUCT16      23.509554
..       ...        ...            ...
764      A65   PRODUCT1      62.388535
765      A65  PRODUCT12    1114.828025
766      A65  PRODUCT14      16.834395
767      A65  PRODUCT33     122.942675
768      A65  PRODUCT34    1780.127389
769      A65  PRODUCT40       9.554140
770      A65  PRODUCT47      23.089172
771      A65  PRODUCT56      88.203822
772      A65  PRODUCT57      91.165605
773      A65  PRODUCT58     181.369427
774      A65  PRODUCT59   12114.452229
775      A65  PRODUCT60      82.159236
776      A65  PRODUCT62     187.605096
777      A66  PRODUCT34     176.936306
778      A66  PRODUCT58       4.789809
779      A66  PRODUCT59    3788.566879
780      A67  PRODUCT34     703.484076
781      A67  PRODUCT58      40.796178
782      A67  PRODUCT59   21489.286624
783      A68  PRODUCT34     290.184713
784      A68  PRODUCT58       1.649682
785      A68  PRODUCT59    7785.178344
786      A69  PRODUCT34     166.184713
787      A69  PRODUCT58       4.611465
788      A69  PRODUCT59    8320.515924
789      A70  PRODUCT34    2165.585987
790      A70  PRODUCT58      61.496815
791      A70  PRODUCT59   69471.617834
792      A77   PRODUCT1    2890.745223
793      A77  PRODUCT12    3473.324841

[794 rows x 3 columns]

In [14]:
selectExample.head()

  regionid    product yearweek      qty
0      A60   PRODUCT4   201402     71.0
1      A60  PRODUCT59   201402  22275.0
2      A60  PRODUCT34   201402   4463.0
3      A60  PRODUCT47   201402      0.0
4      A60  PRODUCT56   201402     23.0

In [17]:
#데이터 조인
mergeData = pd.merge(selectExample, GroupData,\
         on=['regionid','product'], suffixes=('_a','_b'), how="left")
mergeData.head()

  regionid    product yearweek    qty_a         qty_b
0      A60   PRODUCT4   201402     71.0     44.662420
1      A60  PRODUCT59   201402  22275.0  35366.050955
2      A60  PRODUCT34   201402   4463.0   6117.560510
3      A60  PRODUCT47   201402      0.0      0.363057
4      A60  PRODUCT56   201402     23.0     18.560510

In [18]:
mergeData["ratio"] = mergeData["qty_a"]/mergeData["qty_b"]
mergeData.head(10)

  regionid    product yearweek    qty_a         qty_b     ratio
0      A60   PRODUCT4   201402     71.0     44.662420  1.589703
1      A60  PRODUCT59   201402  22275.0  35366.050955  0.629841
2      A60  PRODUCT34   201402   4463.0   6117.560510  0.729539
3      A60  PRODUCT47   201402      0.0      0.363057  0.000000
4      A60  PRODUCT56   201402     23.0     18.560510  1.239190
5      A60  PRODUCT57   201402     14.0    147.248408  0.095077
6      A60  PRODUCT12   201402   1186.0   1216.171975  0.975191
7      A60   PRODUCT1   201402      7.0      3.522293  1.987342
8      A60  PRODUCT33   201402    101.0     60.719745  1.663380
9      A60  PRODUCT62   201402    336.0    328.993631  1.021296

# 피벗 활용하기

In [13]:
# 피벗 예시
pivotResult = selectExample.\
pivot_table(index = ['regionid','product'],columns='yearweek',values='qty')
pivotfinalResult = pivotResult.reset_index()
pivotfinalResult

yearweek,regionid,product,201401,201402,201403,201404,201405,201406,201407,201408,...,201643,201644,201645,201646,201647,201648,201649,201650,201651,201652
0,A00,PRODUCT34,661.0,679.0,578.0,532.0,516.0,423.0,407.0,364.0,...,11.0,15.0,18.0,14.0,9.0,17.0,19.0,35.0,73.0,22.0
1,A00,PRODUCT58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,155.0,213.0,126.0,101.0,141.0,175.0,155.0,104.0,27.0,19.0
2,A00,PRODUCT59,9988.0,9005.0,8416.0,8553.0,10355.0,13799.0,17292.0,16369.0,...,15337.0,19388.0,21567.0,18314.0,19733.0,18127.0,22993.0,26854.0,30237.0,33511.0
3,A01,PRODUCT1,14115.0,9169.0,21350.0,9457.0,10254.0,10327.0,9581.0,10156.0,...,549.0,452.0,531.0,654.0,962.0,789.0,385.0,287.0,292.0,599.0
4,A01,PRODUCT12,139564.0,109173.0,119281.0,139609.0,167828.0,124848.0,157644.0,162431.0,...,158291.0,178978.0,192137.0,441993.0,1663206.0,711806.0,278487.0,320253.0,401602.0,208186.0
5,A01,PRODUCT14,9844.0,6363.0,8022.0,7562.0,6035.0,8858.0,9796.0,10811.0,...,11311.0,18872.0,18153.0,21565.0,49213.0,43209.0,28492.0,26844.0,26835.0,28969.0
6,A01,PRODUCT15,5684.0,4049.0,3689.0,4341.0,3379.0,4208.0,6211.0,3608.0,...,6543.0,2718.0,4465.0,4047.0,3923.0,2786.0,2903.0,3070.0,3856.0,2902.0
7,A01,PRODUCT16,1316.0,919.0,1018.0,905.0,1114.0,991.0,1294.0,1327.0,...,1254.0,1576.0,1459.0,2263.0,5254.0,3324.0,2122.0,2509.0,3339.0,1832.0
8,A01,PRODUCT19,1519.0,2401.0,1513.0,2264.0,2199.0,1428.0,2269.0,1414.0,...,4690.0,3726.0,4254.0,4156.0,4182.0,4003.0,5321.0,4647.0,3837.0,4293.0
9,A01,PRODUCT2,225.0,203.0,236.0,203.0,246.0,277.0,240.0,260.0,...,39328.0,32935.0,28774.0,29125.0,99226.0,64182.0,51715.0,81901.0,60235.0,29640.0
10,A01,PRODUCT20,41.0,6.0,59.0,21.0,22.0,18.0,37.0,23.0,...,23.0,145.0,17.0,43.0,98.0,87.0,92.0,63.0,128.0,15.0
11,A01,PRODUCT33,7043.0,5337.0,6940.0,6041.0,4385.0,4854.0,6519.0,8519.0,...,10964.0,14895.0,20127.0,20619.0,39368.0,35929.0,21721.0,18108.0,19051.0,21213.0
12,A01,PRODUCT34,14836.0,12032.0,13514.0,13798.0,12496.0,18152.0,35577.0,40100.0,...,84873.0,90789.0,90373.0,120137.0,269099.0,192086.0,151447.0,176907.0,777140.0,349574.0
13,A01,PRODUCT4,18722.0,14310.0,17331.0,21018.0,24596.0,17662.0,23494.0,21528.0,...,16690.0,18606.0,20375.0,79539.0,259197.0,85293.0,35088.0,45625.0,77838.0,44429.0
14,A01,PRODUCT47,5650.0,4286.0,4436.0,4167.0,3276.0,3684.0,4931.0,5966.0,...,7194.0,18438.0,25102.0,28749.0,49130.0,36221.0,11500.0,11642.0,10730.0,11207.0
15,A01,PRODUCT56,5000.0,4611.0,5449.0,5436.0,5277.0,5777.0,5964.0,7592.0,...,6281.0,7443.0,7728.0,8530.0,13514.0,11303.0,8732.0,8555.0,8375.0,8308.0
16,A01,PRODUCT57,9660.0,9108.0,13394.0,9196.0,8550.0,8392.0,8763.0,9314.0,...,5035.0,5243.0,5395.0,5426.0,5898.0,5311.0,5250.0,5315.0,5690.0,4863.0
17,A01,PRODUCT58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41252.0,28952.0,27780.0,32775.0,69441.0,66656.0,101974.0,120670.0,112189.0,60303.0
18,A01,PRODUCT59,253391.0,232995.0,237089.0,240723.0,310006.0,331793.0,420826.0,406640.0,...,551038.0,601142.0,585098.0,630040.0,1037853.0,873341.0,749699.0,786380.0,1175605.0,813749.0
19,A01,PRODUCT6,0.0,1.0,0.0,0.0,0.0,6.0,0.0,0.0,...,865.0,1399.0,2209.0,1309.0,21897.0,2314.0,1441.0,1821.0,26930.0,21540.0
20,A01,PRODUCT60,13.0,10.0,4.0,10.0,13.0,5.0,2.0,2.0,...,2.0,1.0,2.0,5.0,0.0,-1.0,2.0,1.0,2.0,1.0
21,A01,PRODUCT62,5987.0,3309.0,3823.0,3325.0,3855.0,7374.0,6679.0,6383.0,...,2418.0,9788.0,8195.0,10691.0,24343.0,20930.0,16540.0,19201.0,18346.0,19507.0
22,A01,PRODUCT63,47708.0,38334.0,31379.0,37305.0,43301.0,35860.0,48170.0,47394.0,...,24203.0,27891.0,26856.0,58242.0,216635.0,101071.0,49184.0,73928.0,115612.0,59716.0
23,A01,PRODUCT7,1153.0,868.0,789.0,792.0,972.0,878.0,1024.0,1401.0,...,4023.0,2908.0,3116.0,4283.0,1675.0,5553.0,4500.0,4343.0,2759.0,5945.0
24,A01,PRODUCT75,15798.0,21562.0,23768.0,23462.0,28700.0,24135.0,27527.0,31742.0,...,31536.0,32115.0,24243.0,33144.0,104559.0,51184.0,27384.0,33227.0,35489.0,21950.0
25,A01,PRODUCT8,164.0,102.0,105.0,258.0,160.0,156.0,110.0,126.0,...,105.0,137.0,633.0,170.0,71.0,291.0,97.0,268.0,121.0,59.0
26,A02,PRODUCT1,321.0,188.0,168.0,75.0,154.0,112.0,142.0,150.0,...,35.0,47.0,36.0,61.0,66.0,64.0,61.0,38.0,61.0,66.0
27,A02,PRODUCT12,9487.0,4874.0,5496.0,4512.0,5507.0,4881.0,5391.0,4570.0,...,8466.0,8216.0,8261.0,15513.0,48994.0,15816.0,9022.0,11320.0,38235.0,33237.0
28,A02,PRODUCT14,2272.0,1149.0,923.0,938.0,1079.0,782.0,978.0,1052.0,...,1775.0,2471.0,1707.0,3704.0,5626.0,2468.0,2014.0,3103.0,4949.0,3610.0
29,A02,PRODUCT16,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,...,41.0,43.0,53.0,143.0,389.0,94.0,76.0,152.0,496.0,188.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
764,A65,PRODUCT1,163.0,131.0,105.0,113.0,99.0,120.0,125.0,108.0,...,9.0,7.0,3.0,6.0,5.0,6.0,5.0,8.0,9.0,18.0
765,A65,PRODUCT12,907.0,898.0,953.0,969.0,1258.0,2299.0,1562.0,1300.0,...,760.0,592.0,790.0,744.0,1294.0,909.0,950.0,1634.0,1565.0,6704.0
766,A65,PRODUCT14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,27.0,19.0,9.0,17.0,27.0,20.0,21.0,15.0,8.0,40.0
767,A65,PRODUCT33,121.0,120.0,115.0,86.0,93.0,101.0,83.0,88.0,...,168.0,69.0,94.0,130.0,192.0,133.0,146.0,155.0,89.0,386.0
768,A65,PRODUCT34,204.0,166.0,204.0,241.0,198.0,243.0,210.0,261.0,...,1283.0,2763.0,1778.0,1207.0,1614.0,1739.0,2877.0,2203.0,7630.0,7161.0
769,A65,PRODUCT40,34.0,27.0,42.0,29.0,30.0,25.0,19.0,25.0,...,16.0,8.0,10.0,10.0,19.0,10.0,13.0,17.0,11.0,44.0
770,A65,PRODUCT47,11.0,19.0,12.0,16.0,20.0,23.0,19.0,15.0,...,30.0,16.0,39.0,40.0,41.0,37.0,49.0,51.0,34.0,242.0
771,A65,PRODUCT56,59.0,87.0,101.0,72.0,46.0,59.0,44.0,59.0,...,95.0,67.0,72.0,51.0,77.0,79.0,87.0,102.0,76.0,167.0
772,A65,PRODUCT57,58.0,94.0,97.0,124.0,301.0,85.0,66.0,104.0,...,97.0,86.0,103.0,93.0,123.0,81.0,116.0,133.0,81.0,378.0
773,A65,PRODUCT58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,264.0,404.0,393.0,405.0,478.0,559.0,617.0,712.0,1099.0,815.0
774,A65,PRODUCT59,3077.0,3109.0,3003.0,3484.0,3463.0,3404.0,4034.0,3750.0,...,13204.0,13140.0,13422.0,13218.0,14906.0,15208.0,18014.0,18611.0,32511.0,25034.0
775,A65,PRODUCT60,58.0,96.0,81.0,62.0,75.0,66.0,55.0,74.0,...,117.0,78.0,68.0,73.0,126.0,89.0,80.0,137.0,62.0,204.0
776,A65,PRODUCT62,183.0,164.0,146.0,197.0,136.0,135.0,114.0,158.0,...,211.0,150.0,146.0,170.0,187.0,119.0,199.0,196.0,130.0,391.0
777,A66,PRODUCT34,65.0,76.0,56.0,53.0,38.0,46.0,67.0,108.0,...,153.0,178.0,169.0,120.0,126.0,159.0,187.0,191.0,183.0,138.0
778,A66,PRODUCT58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,2.0,5.0,9.0,4.0,2.0,3.0,2.0,0.0,0.0
779,A66,PRODUCT59,583.0,609.0,394.0,302.0,303.0,291.0,390.0,488.0,...,2925.0,4606.0,3790.0,3250.0,2513.0,4131.0,3133.0,5327.0,2069.0,2229.0
780,A67,PRODUCT34,457.0,628.0,669.0,650.0,654.0,676.0,684.0,554.0,...,763.0,792.0,765.0,753.0,885.0,903.0,720.0,756.0,1241.0,1008.0
781,A67,PRODUCT58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,16.0,48.0,50.0,32.0,61.0,98.0,167.0,26.0,16.0
782,A67,PRODUCT59,5372.0,7076.0,6931.0,7676.0,7633.0,7417.0,9727.0,11053.0,...,23985.0,18370.0,20529.0,16633.0,20655.0,15305.0,15119.0,18917.0,21887.0,17639.0
783,A68,PRODUCT34,207.0,246.0,191.0,250.0,323.0,335.0,349.0,297.0,...,46.0,45.0,61.0,36.0,38.0,36.0,37.0,30.0,49.0,58.0
784,A68,PRODUCT58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0
785,A68,PRODUCT59,1061.0,1835.0,1356.0,1416.0,1460.0,1608.0,1994.0,2808.0,...,2685.0,2644.0,2570.0,2251.0,2255.0,2051.0,2584.0,2155.0,2237.0,2673.0
786,A69,PRODUCT34,299.0,252.0,210.0,151.0,125.0,105.0,85.0,71.0,...,229.0,206.0,550.0,189.0,210.0,235.0,253.0,232.0,405.0,197.0
787,A69,PRODUCT58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,3.0,0.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0
788,A69,PRODUCT59,697.0,559.0,423.0,386.0,311.0,415.0,583.0,760.0,...,17267.0,15683.0,16916.0,16697.0,14479.0,13823.0,10596.0,11765.0,17916.0,14097.0
789,A70,PRODUCT34,66.0,84.0,67.0,60.0,46.0,53.0,44.0,33.0,...,1903.0,1886.0,2160.0,2490.0,1878.0,1719.0,2645.0,2257.0,1806.0,1479.0
790,A70,PRODUCT58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,80.0,77.0,58.0,31.0,59.0,28.0,47.0,49.0,56.0,56.0
791,A70,PRODUCT59,341.0,334.0,298.0,309.0,351.0,367.0,315.0,276.0,...,102679.0,96626.0,88457.0,75856.0,82654.0,72010.0,84632.0,85369.0,97324.0,100067.0
792,A77,PRODUCT1,3580.0,2465.0,2205.0,1623.0,1482.0,4735.0,3633.0,4466.0,...,3790.0,2450.0,2925.0,2998.0,2920.0,3070.0,4222.0,4422.0,3671.0,2759.0
793,A77,PRODUCT12,3821.0,2466.0,2401.0,2628.0,1442.0,3794.0,2409.0,2619.0,...,5760.0,4109.0,4506.0,4255.0,3574.0,4152.0,5086.0,5846.0,4933.0,7551.0

In [12]:
# 피벗 예시
pivotResult = selectExample.\
pivot_table(index = ['regionid','product'],columns='yearweek',values='qty')
pivotfinalResult = pivotResult.reset_index(drop=True)
pivotfinalResult

yearweek,201401,201402,201403,201404,201405,201406,201407,201408,201409,201410,...,201643,201644,201645,201646,201647,201648,201649,201650,201651,201652
0,661.0,679.0,578.0,532.0,516.0,423.0,407.0,364.0,470.0,538.0,...,11.0,15.0,18.0,14.0,9.0,17.0,19.0,35.0,73.0,22.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,155.0,213.0,126.0,101.0,141.0,175.0,155.0,104.0,27.0,19.0
2,9988.0,9005.0,8416.0,8553.0,10355.0,13799.0,17292.0,16369.0,15047.0,15895.0,...,15337.0,19388.0,21567.0,18314.0,19733.0,18127.0,22993.0,26854.0,30237.0,33511.0
3,14115.0,9169.0,21350.0,9457.0,10254.0,10327.0,9581.0,10156.0,9045.0,8141.0,...,549.0,452.0,531.0,654.0,962.0,789.0,385.0,287.0,292.0,599.0
4,139564.0,109173.0,119281.0,139609.0,167828.0,124848.0,157644.0,162431.0,147877.0,145733.0,...,158291.0,178978.0,192137.0,441993.0,1663206.0,711806.0,278487.0,320253.0,401602.0,208186.0
5,9844.0,6363.0,8022.0,7562.0,6035.0,8858.0,9796.0,10811.0,9000.0,9286.0,...,11311.0,18872.0,18153.0,21565.0,49213.0,43209.0,28492.0,26844.0,26835.0,28969.0
6,5684.0,4049.0,3689.0,4341.0,3379.0,4208.0,6211.0,3608.0,3824.0,3694.0,...,6543.0,2718.0,4465.0,4047.0,3923.0,2786.0,2903.0,3070.0,3856.0,2902.0
7,1316.0,919.0,1018.0,905.0,1114.0,991.0,1294.0,1327.0,988.0,965.0,...,1254.0,1576.0,1459.0,2263.0,5254.0,3324.0,2122.0,2509.0,3339.0,1832.0
8,1519.0,2401.0,1513.0,2264.0,2199.0,1428.0,2269.0,1414.0,2544.0,2064.0,...,4690.0,3726.0,4254.0,4156.0,4182.0,4003.0,5321.0,4647.0,3837.0,4293.0
9,225.0,203.0,236.0,203.0,246.0,277.0,240.0,260.0,314.0,330.0,...,39328.0,32935.0,28774.0,29125.0,99226.0,64182.0,51715.0,81901.0,60235.0,29640.0
10,41.0,6.0,59.0,21.0,22.0,18.0,37.0,23.0,33.0,7.0,...,23.0,145.0,17.0,43.0,98.0,87.0,92.0,63.0,128.0,15.0
11,7043.0,5337.0,6940.0,6041.0,4385.0,4854.0,6519.0,8519.0,8135.0,7632.0,...,10964.0,14895.0,20127.0,20619.0,39368.0,35929.0,21721.0,18108.0,19051.0,21213.0
12,14836.0,12032.0,13514.0,13798.0,12496.0,18152.0,35577.0,40100.0,38850.0,31439.0,...,84873.0,90789.0,90373.0,120137.0,269099.0,192086.0,151447.0,176907.0,777140.0,349574.0
13,18722.0,14310.0,17331.0,21018.0,24596.0,17662.0,23494.0,21528.0,19137.0,16086.0,...,16690.0,18606.0,20375.0,79539.0,259197.0,85293.0,35088.0,45625.0,77838.0,44429.0
14,5650.0,4286.0,4436.0,4167.0,3276.0,3684.0,4931.0,5966.0,4175.0,4187.0,...,7194.0,18438.0,25102.0,28749.0,49130.0,36221.0,11500.0,11642.0,10730.0,11207.0
15,5000.0,4611.0,5449.0,5436.0,5277.0,5777.0,5964.0,7592.0,7003.0,6849.0,...,6281.0,7443.0,7728.0,8530.0,13514.0,11303.0,8732.0,8555.0,8375.0,8308.0
16,9660.0,9108.0,13394.0,9196.0,8550.0,8392.0,8763.0,9314.0,8571.0,7857.0,...,5035.0,5243.0,5395.0,5426.0,5898.0,5311.0,5250.0,5315.0,5690.0,4863.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41252.0,28952.0,27780.0,32775.0,69441.0,66656.0,101974.0,120670.0,112189.0,60303.0
18,253391.0,232995.0,237089.0,240723.0,310006.0,331793.0,420826.0,406640.0,379845.0,384239.0,...,551038.0,601142.0,585098.0,630040.0,1037853.0,873341.0,749699.0,786380.0,1175605.0,813749.0
19,0.0,1.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,1.0,...,865.0,1399.0,2209.0,1309.0,21897.0,2314.0,1441.0,1821.0,26930.0,21540.0
20,13.0,10.0,4.0,10.0,13.0,5.0,2.0,2.0,-2.0,3.0,...,2.0,1.0,2.0,5.0,0.0,-1.0,2.0,1.0,2.0,1.0
21,5987.0,3309.0,3823.0,3325.0,3855.0,7374.0,6679.0,6383.0,4571.0,5503.0,...,2418.0,9788.0,8195.0,10691.0,24343.0,20930.0,16540.0,19201.0,18346.0,19507.0
22,47708.0,38334.0,31379.0,37305.0,43301.0,35860.0,48170.0,47394.0,42695.0,40494.0,...,24203.0,27891.0,26856.0,58242.0,216635.0,101071.0,49184.0,73928.0,115612.0,59716.0
23,1153.0,868.0,789.0,792.0,972.0,878.0,1024.0,1401.0,978.0,1245.0,...,4023.0,2908.0,3116.0,4283.0,1675.0,5553.0,4500.0,4343.0,2759.0,5945.0
24,15798.0,21562.0,23768.0,23462.0,28700.0,24135.0,27527.0,31742.0,25819.0,30186.0,...,31536.0,32115.0,24243.0,33144.0,104559.0,51184.0,27384.0,33227.0,35489.0,21950.0
25,164.0,102.0,105.0,258.0,160.0,156.0,110.0,126.0,115.0,81.0,...,105.0,137.0,633.0,170.0,71.0,291.0,97.0,268.0,121.0,59.0
26,321.0,188.0,168.0,75.0,154.0,112.0,142.0,150.0,244.0,151.0,...,35.0,47.0,36.0,61.0,66.0,64.0,61.0,38.0,61.0,66.0
27,9487.0,4874.0,5496.0,4512.0,5507.0,4881.0,5391.0,4570.0,5437.0,4243.0,...,8466.0,8216.0,8261.0,15513.0,48994.0,15816.0,9022.0,11320.0,38235.0,33237.0
28,2272.0,1149.0,923.0,938.0,1079.0,782.0,978.0,1052.0,1256.0,1276.0,...,1775.0,2471.0,1707.0,3704.0,5626.0,2468.0,2014.0,3103.0,4949.0,3610.0
29,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41.0,43.0,53.0,143.0,389.0,94.0,76.0,152.0,496.0,188.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
764,163.0,131.0,105.0,113.0,99.0,120.0,125.0,108.0,125.0,92.0,...,9.0,7.0,3.0,6.0,5.0,6.0,5.0,8.0,9.0,18.0
765,907.0,898.0,953.0,969.0,1258.0,2299.0,1562.0,1300.0,1527.0,1669.0,...,760.0,592.0,790.0,744.0,1294.0,909.0,950.0,1634.0,1565.0,6704.0
766,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,27.0,19.0,9.0,17.0,27.0,20.0,21.0,15.0,8.0,40.0
767,121.0,120.0,115.0,86.0,93.0,101.0,83.0,88.0,160.0,170.0,...,168.0,69.0,94.0,130.0,192.0,133.0,146.0,155.0,89.0,386.0
768,204.0,166.0,204.0,241.0,198.0,243.0,210.0,261.0,364.0,300.0,...,1283.0,2763.0,1778.0,1207.0,1614.0,1739.0,2877.0,2203.0,7630.0,7161.0
769,34.0,27.0,42.0,29.0,30.0,25.0,19.0,25.0,55.0,40.0,...,16.0,8.0,10.0,10.0,19.0,10.0,13.0,17.0,11.0,44.0
770,11.0,19.0,12.0,16.0,20.0,23.0,19.0,15.0,16.0,19.0,...,30.0,16.0,39.0,40.0,41.0,37.0,49.0,51.0,34.0,242.0
771,59.0,87.0,101.0,72.0,46.0,59.0,44.0,59.0,88.0,69.0,...,95.0,67.0,72.0,51.0,77.0,79.0,87.0,102.0,76.0,167.0
772,58.0,94.0,97.0,124.0,301.0,85.0,66.0,104.0,84.0,67.0,...,97.0,86.0,103.0,93.0,123.0,81.0,116.0,133.0,81.0,378.0
773,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,264.0,404.0,393.0,405.0,478.0,559.0,617.0,712.0,1099.0,815.0
774,3077.0,3109.0,3003.0,3484.0,3463.0,3404.0,4034.0,3750.0,4445.0,4692.0,...,13204.0,13140.0,13422.0,13218.0,14906.0,15208.0,18014.0,18611.0,32511.0,25034.0
775,58.0,96.0,81.0,62.0,75.0,66.0,55.0,74.0,69.0,72.0,...,117.0,78.0,68.0,73.0,126.0,89.0,80.0,137.0,62.0,204.0
776,183.0,164.0,146.0,197.0,136.0,135.0,114.0,158.0,140.0,139.0,...,211.0,150.0,146.0,170.0,187.0,119.0,199.0,196.0,130.0,391.0
777,65.0,76.0,56.0,53.0,38.0,46.0,67.0,108.0,152.0,146.0,...,153.0,178.0,169.0,120.0,126.0,159.0,187.0,191.0,183.0,138.0
778,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,2.0,5.0,9.0,4.0,2.0,3.0,2.0,0.0,0.0
779,583.0,609.0,394.0,302.0,303.0,291.0,390.0,488.0,740.0,570.0,...,2925.0,4606.0,3790.0,3250.0,2513.0,4131.0,3133.0,5327.0,2069.0,2229.0
780,457.0,628.0,669.0,650.0,654.0,676.0,684.0,554.0,543.0,482.0,...,763.0,792.0,765.0,753.0,885.0,903.0,720.0,756.0,1241.0,1008.0
781,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,16.0,48.0,50.0,32.0,61.0,98.0,167.0,26.0,16.0
782,5372.0,7076.0,6931.0,7676.0,7633.0,7417.0,9727.0,11053.0,11145.0,13226.0,...,23985.0,18370.0,20529.0,16633.0,20655.0,15305.0,15119.0,18917.0,21887.0,17639.0
783,207.0,246.0,191.0,250.0,323.0,335.0,349.0,297.0,375.0,391.0,...,46.0,45.0,61.0,36.0,38.0,36.0,37.0,30.0,49.0,58.0
784,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0
785,1061.0,1835.0,1356.0,1416.0,1460.0,1608.0,1994.0,2808.0,1918.0,2065.0,...,2685.0,2644.0,2570.0,2251.0,2255.0,2051.0,2584.0,2155.0,2237.0,2673.0
786,299.0,252.0,210.0,151.0,125.0,105.0,85.0,71.0,132.0,93.0,...,229.0,206.0,550.0,189.0,210.0,235.0,253.0,232.0,405.0,197.0
787,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,3.0,0.0,1.0,1.0,1.0,3.0,1.0,1.0,2.0
788,697.0,559.0,423.0,386.0,311.0,415.0,583.0,760.0,864.0,872.0,...,17267.0,15683.0,16916.0,16697.0,14479.0,13823.0,10596.0,11765.0,17916.0,14097.0
789,66.0,84.0,67.0,60.0,46.0,53.0,44.0,33.0,28.0,33.0,...,1903.0,1886.0,2160.0,2490.0,1878.0,1719.0,2645.0,2257.0,1806.0,1479.0
790,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,80.0,77.0,58.0,31.0,59.0,28.0,47.0,49.0,56.0,56.0
791,341.0,334.0,298.0,309.0,351.0,367.0,315.0,276.0,165.0,139.0,...,102679.0,96626.0,88457.0,75856.0,82654.0,72010.0,84632.0,85369.0,97324.0,100067.0
792,3580.0,2465.0,2205.0,1623.0,1482.0,4735.0,3633.0,4466.0,3293.0,2942.0,...,3790.0,2450.0,2925.0,2998.0,2920.0,3070.0,4222.0,4422.0,3671.0,2759.0
793,3821.0,2466.0,2401.0,2628.0,1442.0,3794.0,2409.0,2619.0,2587.0,2038.0,...,5760.0,4109.0,4506.0,4255.0,3574.0,4152.0,5086.0,5846.0,4933.0,7551.0

In [14]:
# 피벗 인덱스 리셋 제거
pivotResult = selectExample.\
pivot_table(index = ['regionid','product'],columns='yearweek',values='qty')
pivotfinalResult = pivotResult
pivotfinalResult

yearweek              201401    201402    201403    201404    201405  \
regionid product
A00      PRODUCT34     661.0     679.0     578.0     532.0     516.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59    9988.0    9005.0    8416.0    8553.0   10355.0
A01      PRODUCT1    14115.0    9169.0   21350.0    9457.0   10254.0
         PRODUCT12  139564.0  109173.0  119281.0  139609.0  167828.0
         PRODUCT14    9844.0    6363.0    8022.0    7562.0    6035.0
         PRODUCT15    5684.0    4049.0    3689.0    4341.0    3379.0
         PRODUCT16    1316.0     919.0    1018.0     905.0    1114.0
         PRODUCT19    1519.0    2401.0    1513.0    2264.0    2199.0
         PRODUCT2      225.0     203.0     236.0     203.0     246.0
         PRODUCT20      41.0       6.0      59.0      21.0      22.0
         PRODUCT33    7043.0    5337.0    6940.0    6041.0    4385.0
         PRODUCT34   14836.0   12032.0   13514.0   13798.0   12496.0
         PRODUCT4    18722.0   14310.0   17331.0   21018.0   24596.0
         PRODUCT47    5650.0    4286.0    4436.0    4167.0    3276.0
         PRODUCT56    5000.0    4611.0    5449.0    5436.0    5277.0
         PRODUCT57    9660.0    9108.0   13394.0    9196.0    8550.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59  253391.0  232995.0  237089.0  240723.0  310006.0
         PRODUCT6        0.0       1.0       0.0       0.0       0.0
         PRODUCT60      13.0      10.0       4.0      10.0      13.0
         PRODUCT62    5987.0    3309.0    3823.0    3325.0    3855.0
         PRODUCT63   47708.0   38334.0   31379.0   37305.0   43301.0
         PRODUCT7     1153.0     868.0     789.0     792.0     972.0
         PRODUCT75   15798.0   21562.0   23768.0   23462.0   28700.0
         PRODUCT8      164.0     102.0     105.0     258.0     160.0
A02      PRODUCT1      321.0     188.0     168.0      75.0     154.0
         PRODUCT12    9487.0    4874.0    5496.0    4512.0    5507.0
         PRODUCT14    2272.0    1149.0     923.0     938.0    1079.0
         PRODUCT16       0.0       0.0      -1.0       0.0       0.0
...                      ...       ...       ...       ...       ...
A65      PRODUCT1      163.0     131.0     105.0     113.0      99.0
         PRODUCT12     907.0     898.0     953.0     969.0    1258.0
         PRODUCT14       0.0       0.0       0.0       0.0       0.0
         PRODUCT33     121.0     120.0     115.0      86.0      93.0
         PRODUCT34     204.0     166.0     204.0     241.0     198.0
         PRODUCT40      34.0      27.0      42.0      29.0      30.0
         PRODUCT47      11.0      19.0      12.0      16.0      20.0
         PRODUCT56      59.0      87.0     101.0      72.0      46.0
         PRODUCT57      58.0      94.0      97.0     124.0     301.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59    3077.0    3109.0    3003.0    3484.0    3463.0
         PRODUCT60      58.0      96.0      81.0      62.0      75.0
         PRODUCT62     183.0     164.0     146.0     197.0     136.0
A66      PRODUCT34      65.0      76.0      56.0      53.0      38.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59     583.0     609.0     394.0     302.0     303.0
A67      PRODUCT34     457.0     628.0     669.0     650.0     654.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59    5372.0    7076.0    6931.0    7676.0    7633.0
A68      PRODUCT34     207.0     246.0     191.0     250.0     323.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59    1061.0    1835.0    1356.0    1416.0    1460.0
A69      PRODUCT34     299.0     252.0     210.0     151.0     125.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59     697.0     559.0     423.0     386.0     311.0
A70      PRODUCT34      66.0      84.0      67.0      60.0      46.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59     341.0     334.0     298.0     309.0     351.0
A77      PRODUCT1     3580.0    2465.0    2205.0    1623.0    1482.0
         PRODUCT12    3821.0    2466.0    2401.0    2628.0    1442.0

yearweek              201406    201407    201408    201409    201410  \
regionid product
A00      PRODUCT34     423.0     407.0     364.0     470.0     538.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59   13799.0   17292.0   16369.0   15047.0   15895.0
A01      PRODUCT1    10327.0    9581.0   10156.0    9045.0    8141.0
         PRODUCT12  124848.0  157644.0  162431.0  147877.0  145733.0
         PRODUCT14    8858.0    9796.0   10811.0    9000.0    9286.0
         PRODUCT15    4208.0    6211.0    3608.0    3824.0    3694.0
         PRODUCT16     991.0    1294.0    1327.0     988.0     965.0
         PRODUCT19    1428.0    2269.0    1414.0    2544.0    2064.0
         PRODUCT2      277.0     240.0     260.0     314.0     330.0
         PRODUCT20      18.0      37.0      23.0      33.0       7.0
         PRODUCT33    4854.0    6519.0    8519.0    8135.0    7632.0
         PRODUCT34   18152.0   35577.0   40100.0   38850.0   31439.0
         PRODUCT4    17662.0   23494.0   21528.0   19137.0   16086.0
         PRODUCT47    3684.0    4931.0    5966.0    4175.0    4187.0
         PRODUCT56    5777.0    5964.0    7592.0    7003.0    6849.0
         PRODUCT57    8392.0    8763.0    9314.0    8571.0    7857.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59  331793.0  420826.0  406640.0  379845.0  384239.0
         PRODUCT6        6.0       0.0       0.0       0.0       1.0
         PRODUCT60       5.0       2.0       2.0      -2.0       3.0
         PRODUCT62    7374.0    6679.0    6383.0    4571.0    5503.0
         PRODUCT63   35860.0   48170.0   47394.0   42695.0   40494.0
         PRODUCT7      878.0    1024.0    1401.0     978.0    1245.0
         PRODUCT75   24135.0   27527.0   31742.0   25819.0   30186.0
         PRODUCT8      156.0     110.0     126.0     115.0      81.0
A02      PRODUCT1      112.0     142.0     150.0     244.0     151.0
         PRODUCT12    4881.0    5391.0    4570.0    5437.0    4243.0
         PRODUCT14     782.0     978.0    1052.0    1256.0    1276.0
         PRODUCT16       0.0       0.0       0.0       0.0       0.0
...                      ...       ...       ...       ...       ...
A65      PRODUCT1      120.0     125.0     108.0     125.0      92.0
         PRODUCT12    2299.0    1562.0    1300.0    1527.0    1669.0
         PRODUCT14       0.0       0.0       0.0       0.0       0.0
         PRODUCT33     101.0      83.0      88.0     160.0     170.0
         PRODUCT34     243.0     210.0     261.0     364.0     300.0
         PRODUCT40      25.0      19.0      25.0      55.0      40.0
         PRODUCT47      23.0      19.0      15.0      16.0      19.0
         PRODUCT56      59.0      44.0      59.0      88.0      69.0
         PRODUCT57      85.0      66.0     104.0      84.0      67.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59    3404.0    4034.0    3750.0    4445.0    4692.0
         PRODUCT60      66.0      55.0      74.0      69.0      72.0
         PRODUCT62     135.0     114.0     158.0     140.0     139.0
A66      PRODUCT34      46.0      67.0     108.0     152.0     146.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59     291.0     390.0     488.0     740.0     570.0
A67      PRODUCT34     676.0     684.0     554.0     543.0     482.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59    7417.0    9727.0   11053.0   11145.0   13226.0
A68      PRODUCT34     335.0     349.0     297.0     375.0     391.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59    1608.0    1994.0    2808.0    1918.0    2065.0
A69      PRODUCT34     105.0      85.0      71.0     132.0      93.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59     415.0     583.0     760.0     864.0     872.0
A70      PRODUCT34      53.0      44.0      33.0      28.0      33.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59     367.0     315.0     276.0     165.0     139.0
A77      PRODUCT1     4735.0    3633.0    4466.0    3293.0    2942.0
         PRODUCT12    3794.0    2409.0    2619.0    2587.0    2038.0

yearweek              ...       201643    201644    201645    201646  \
regionid product      ...
A00      PRODUCT34    ...         11.0      15.0      18.0      14.0
         PRODUCT58    ...        155.0     213.0     126.0     101.0
         PRODUCT59    ...      15337.0   19388.0   21567.0   18314.0
A01      PRODUCT1     ...        549.0     452.0     531.0     654.0
         PRODUCT12    ...     158291.0  178978.0  192137.0  441993.0
         PRODUCT14    ...      11311.0   18872.0   18153.0   21565.0
         PRODUCT15    ...       6543.0    2718.0    4465.0    4047.0
         PRODUCT16    ...       1254.0    1576.0    1459.0    2263.0
         PRODUCT19    ...       4690.0    3726.0    4254.0    4156.0
         PRODUCT2     ...      39328.0   32935.0   28774.0   29125.0
         PRODUCT20    ...         23.0     145.0      17.0      43.0
         PRODUCT33    ...      10964.0   14895.0   20127.0   20619.0
         PRODUCT34    ...      84873.0   90789.0   90373.0  120137.0
         PRODUCT4     ...      16690.0   18606.0   20375.0   79539.0
         PRODUCT47    ...       7194.0   18438.0   25102.0   28749.0
         PRODUCT56    ...       6281.0    7443.0    7728.0    8530.0
         PRODUCT57    ...       5035.0    5243.0    5395.0    5426.0
         PRODUCT58    ...      41252.0   28952.0   27780.0   32775.0
         PRODUCT59    ...     551038.0  601142.0  585098.0  630040.0
         PRODUCT6     ...        865.0    1399.0    2209.0    1309.0
         PRODUCT60    ...          2.0       1.0       2.0       5.0
         PRODUCT62    ...       2418.0    9788.0    8195.0   10691.0
         PRODUCT63    ...      24203.0   27891.0   26856.0   58242.0
         PRODUCT7     ...       4023.0    2908.0    3116.0    4283.0
         PRODUCT75    ...      31536.0   32115.0   24243.0   33144.0
         PRODUCT8     ...        105.0     137.0     633.0     170.0
A02      PRODUCT1     ...         35.0      47.0      36.0      61.0
         PRODUCT12    ...       8466.0    8216.0    8261.0   15513.0
         PRODUCT14    ...       1775.0    2471.0    1707.0    3704.0
         PRODUCT16    ...         41.0      43.0      53.0     143.0
...                   ...          ...       ...       ...       ...
A65      PRODUCT1     ...          9.0       7.0       3.0       6.0
         PRODUCT12    ...        760.0     592.0     790.0     744.0
         PRODUCT14    ...         27.0      19.0       9.0      17.0
         PRODUCT33    ...        168.0      69.0      94.0     130.0
         PRODUCT34    ...       1283.0    2763.0    1778.0    1207.0
         PRODUCT40    ...         16.0       8.0      10.0      10.0
         PRODUCT47    ...         30.0      16.0      39.0      40.0
         PRODUCT56    ...         95.0      67.0      72.0      51.0
         PRODUCT57    ...         97.0      86.0     103.0      93.0
         PRODUCT58    ...        264.0     404.0     393.0     405.0
         PRODUCT59    ...      13204.0   13140.0   13422.0   13218.0
         PRODUCT60    ...        117.0      78.0      68.0      73.0
         PRODUCT62    ...        211.0     150.0     146.0     170.0
A66      PRODUCT34    ...        153.0     178.0     169.0     120.0
         PRODUCT58    ...          1.0       2.0       5.0       9.0
         PRODUCT59    ...       2925.0    4606.0    3790.0    3250.0
A67      PRODUCT34    ...        763.0     792.0     765.0     753.0
         PRODUCT58    ...         10.0      16.0      48.0      50.0
         PRODUCT59    ...      23985.0   18370.0   20529.0   16633.0
A68      PRODUCT34    ...         46.0      45.0      61.0      36.0
         PRODUCT58    ...          2.0       1.0       0.0       0.0
         PRODUCT59    ...       2685.0    2644.0    2570.0    2251.0
A69      PRODUCT34    ...        229.0     206.0     550.0     189.0
         PRODUCT58    ...          1.0       3.0       0.0       1.0
         PRODUCT59    ...      17267.0   15683.0   16916.0   16697.0
A70      PRODUCT34    ...       1903.0    1886.0    2160.0    2490.0
         PRODUCT58    ...         80.0      77.0      58.0      31.0
         PRODUCT59    ...     102679.0   96626.0   88457.0   75856.0
A77      PRODUCT1     ...       3790.0    2450.0    2925.0    2998.0
         PRODUCT12    ...       5760.0    4109.0    4506.0    4255.0

yearweek               201647    201648    201649    201650     201651  \
regionid product
A00      PRODUCT34        9.0      17.0      19.0      35.0       73.0
         PRODUCT58      141.0     175.0     155.0     104.0       27.0
         PRODUCT59    19733.0   18127.0   22993.0   26854.0    30237.0
A01      PRODUCT1       962.0     789.0     385.0     287.0      292.0
         PRODUCT12  1663206.0  711806.0  278487.0  320253.0   401602.0
         PRODUCT14    49213.0   43209.0   28492.0   26844.0    26835.0
         PRODUCT15     3923.0    2786.0    2903.0    3070.0     3856.0
         PRODUCT16     5254.0    3324.0    2122.0    2509.0     3339.0
         PRODUCT19     4182.0    4003.0    5321.0    4647.0     3837.0
         PRODUCT2     99226.0   64182.0   51715.0   81901.0    60235.0
         PRODUCT20       98.0      87.0      92.0      63.0      128.0
         PRODUCT33    39368.0   35929.0   21721.0   18108.0    19051.0
         PRODUCT34   269099.0  192086.0  151447.0  176907.0   777140.0
         PRODUCT4    259197.0   85293.0   35088.0   45625.0    77838.0
         PRODUCT47    49130.0   36221.0   11500.0   11642.0    10730.0
         PRODUCT56    13514.0   11303.0    8732.0    8555.0     8375.0
         PRODUCT57     5898.0    5311.0    5250.0    5315.0     5690.0
         PRODUCT58    69441.0   66656.0  101974.0  120670.0   112189.0
         PRODUCT59  1037853.0  873341.0  749699.0  786380.0  1175605.0
         PRODUCT6     21897.0    2314.0    1441.0    1821.0    26930.0
         PRODUCT60        0.0      -1.0       2.0       1.0        2.0
         PRODUCT62    24343.0   20930.0   16540.0   19201.0    18346.0
         PRODUCT63   216635.0  101071.0   49184.0   73928.0   115612.0
         PRODUCT7      1675.0    5553.0    4500.0    4343.0     2759.0
         PRODUCT75   104559.0   51184.0   27384.0   33227.0    35489.0
         PRODUCT8        71.0     291.0      97.0     268.0      121.0
A02      PRODUCT1        66.0      64.0      61.0      38.0       61.0
         PRODUCT12    48994.0   15816.0    9022.0   11320.0    38235.0
         PRODUCT14     5626.0    2468.0    2014.0    3103.0     4949.0
         PRODUCT16      389.0      94.0      76.0     152.0      496.0
...                       ...       ...       ...       ...        ...
A65      PRODUCT1         5.0       6.0       5.0       8.0        9.0
         PRODUCT12     1294.0     909.0     950.0    1634.0     1565.0
         PRODUCT14       27.0      20.0      21.0      15.0        8.0
         PRODUCT33      192.0     133.0     146.0     155.0       89.0
         PRODUCT34     1614.0    1739.0    2877.0    2203.0     7630.0
         PRODUCT40       19.0      10.0      13.0      17.0       11.0
         PRODUCT47       41.0      37.0      49.0      51.0       34.0
         PRODUCT56       77.0      79.0      87.0     102.0       76.0
         PRODUCT57      123.0      81.0     116.0     133.0       81.0
         PRODUCT58      478.0     559.0     617.0     712.0     1099.0
         PRODUCT59    14906.0   15208.0   18014.0   18611.0    32511.0
         PRODUCT60      126.0      89.0      80.0     137.0       62.0
         PRODUCT62      187.0     119.0     199.0     196.0      130.0
A66      PRODUCT34      126.0     159.0     187.0     191.0      183.0
         PRODUCT58        4.0       2.0       3.0       2.0        0.0
         PRODUCT59     2513.0    4131.0    3133.0    5327.0     2069.0
A67      PRODUCT34      885.0     903.0     720.0     756.0     1241.0
         PRODUCT58       32.0      61.0      98.0     167.0       26.0
         PRODUCT59    20655.0   15305.0   15119.0   18917.0    21887.0
A68      PRODUCT34       38.0      36.0      37.0      30.0       49.0
         PRODUCT58        2.0       0.0       1.0       0.0        0.0
         PRODUCT59     2255.0    2051.0    2584.0    2155.0     2237.0
A69      PRODUCT34      210.0     235.0     253.0     232.0      405.0
         PRODUCT58        1.0       1.0       3.0       1.0        1.0
         PRODUCT59    14479.0   13823.0   10596.0   11765.0    17916.0
A70      PRODUCT34     1878.0    1719.0    2645.0    2257.0     1806.0
         PRODUCT58       59.0      28.0      47.0      49.0       56.0
         PRODUCT59    82654.0   72010.0   84632.0   85369.0    97324.0
A77      PRODUCT1      2920.0    3070.0    4222.0    4422.0     3671.0
         PRODUCT12     3574.0    4152.0    5086.0    5846.0     4933.0

yearweek              201652
regionid product
A00      PRODUCT34      22.0
         PRODUCT58      19.0
         PRODUCT59   33511.0
A01      PRODUCT1      599.0
         PRODUCT12  208186.0
         PRODUCT14   28969.0
         PRODUCT15    2902.0
         PRODUCT16    1832.0
         PRODUCT19    4293.0
         PRODUCT2    29640.0
         PRODUCT20      15.0
         PRODUCT33   21213.0
         PRODUCT34  349574.0
         PRODUCT4    44429.0
         PRODUCT47   11207.0
         PRODUCT56    8308.0
         PRODUCT57    4863.0
         PRODUCT58   60303.0
         PRODUCT59  813749.0
         PRODUCT6    21540.0
         PRODUCT60       1.0
         PRODUCT62   19507.0
         PRODUCT63   59716.0
         PRODUCT7     5945.0
         PRODUCT75   21950.0
         PRODUCT8       59.0
A02      PRODUCT1       66.0
         PRODUCT12   33237.0
         PRODUCT14    3610.0
         PRODUCT16     188.0
...                      ...
A65      PRODUCT1       18.0
         PRODUCT12    6704.0
         PRODUCT14      40.0
         PRODUCT33     386.0
         PRODUCT34    7161.0
         PRODUCT40      44.0
         PRODUCT47     242.0
         PRODUCT56     167.0
         PRODUCT57     378.0
         PRODUCT58     815.0
         PRODUCT59   25034.0
         PRODUCT60     204.0
         PRODUCT62     391.0
A66      PRODUCT34     138.0
         PRODUCT58       0.0
         PRODUCT59    2229.0
A67      PRODUCT34    1008.0
         PRODUCT58      16.0
         PRODUCT59   17639.0
A68      PRODUCT34      58.0
         PRODUCT58       0.0
         PRODUCT59    2673.0
A69      PRODUCT34     197.0
         PRODUCT58       2.0
         PRODUCT59   14097.0
A70      PRODUCT34    1479.0
         PRODUCT58      56.0
         PRODUCT59  100067.0
A77      PRODUCT1     2759.0
         PRODUCT12    7551.0

[794 rows x 157 columns]

In [27]:
#  피벗 예시
pivotResult = selectExample.\
pivot_table(index = ['regionid','product'], columns='yearweek', values='qty')
pivotResult.reset_index()
pivotResult.columns

Index(['201401', '201402', '201403', '201404', '201405', '201406', '201407',
       '201408', '201409', '201410',
       ...
       '201643', '201644', '201645', '201646', '201647', '201648', '201649',
       '201650', '201651', '201652'],
      dtype='object', name='yearweek', length=157)

In [28]:
pivotResult.head()

yearweek              201401    201402    201403    201404    201405  \
regionid product
A00      PRODUCT34     661.0     679.0     578.0     532.0     516.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59    9988.0    9005.0    8416.0    8553.0   10355.0
A01      PRODUCT1    14115.0    9169.0   21350.0    9457.0   10254.0
         PRODUCT12  139564.0  109173.0  119281.0  139609.0  167828.0

yearweek              201406    201407    201408    201409    201410  \
regionid product
A00      PRODUCT34     423.0     407.0     364.0     470.0     538.0
         PRODUCT58       0.0       0.0       0.0       0.0       0.0
         PRODUCT59   13799.0   17292.0   16369.0   15047.0   15895.0
A01      PRODUCT1    10327.0    9581.0   10156.0    9045.0    8141.0
         PRODUCT12  124848.0  157644.0  162431.0  147877.0  145733.0

yearweek              ...       201643    201644    201645    201646  \
regionid product      ...
A00      PRODUCT34    ...         11.0      15.0      18.0      14.0
         PRODUCT58    ...        155.0     213.0     126.0     101.0
         PRODUCT59    ...      15337.0   19388.0   21567.0   18314.0
A01      PRODUCT1     ...        549.0     452.0     531.0     654.0
         PRODUCT12    ...     158291.0  178978.0  192137.0  441993.0

yearweek               201647    201648    201649    201650    201651  \
regionid product
A00      PRODUCT34        9.0      17.0      19.0      35.0      73.0
         PRODUCT58      141.0     175.0     155.0     104.0      27.0
         PRODUCT59    19733.0   18127.0   22993.0   26854.0   30237.0
A01      PRODUCT1       962.0     789.0     385.0     287.0     292.0
         PRODUCT12  1663206.0  711806.0  278487.0  320253.0  401602.0

yearweek              201652
regionid product
A00      PRODUCT34      22.0
         PRODUCT58      19.0
         PRODUCT59   33511.0
A01      PRODUCT1      599.0
         PRODUCT12  208186.0

[5 rows x 157 columns]

In [29]:
unpivotResult=pivotResult.stack().reset_index()
unpivotResult.columns=\
['regionid','product','yearweek','qty']

unpivotResult.head()

  regionid    product yearweek    qty
0      A00  PRODUCT34   201401  661.0
1      A00  PRODUCT34   201402  679.0
2      A00  PRODUCT34   201403  578.0
3      A00  PRODUCT34   201404  532.0
4      A00  PRODUCT34   201405  516.0